env:
  TERM: xterm-256color

window:
  #dimensions:
  #  columns: 0
  #  lines: 0
  #position:
  #  x: 0
  #  y: 0
  padding:
    x: 2
    y: 4
  decorations: full
  startup_mode: Maximized
  title: WolfenCLI Terminal
  class:
    # Application instance name
    instance: Alacritty
    # General application class
    general: Alacritty
  gtk_theme_variant: dark

  dynamic_title: true

#scrolling:
  #history: 10000
  #multiplier: 3

font:
  #normal:
    #family: monospace
    #style: Regular
  #bold:
    #family: monospace
    #style: Bold
  #italic:
    #family: monospace
    #style: Italic
  #bold_italic:
    #family: monospace
    #style: Bold Italic
  size: 6.5
  #offset:
  #  x: 0
  #  y: 0
  #glyph_offset:
  #  x: 0
  #  y: 0

#draw_bold_text_with_bright_colors: false

#colors:
  #primary:
  #  background: '0x000000'
  #  foreground: '0xeaeaea'
  #  dim_foreground: '0x9a9a9a'
  #  bright_foreground: '0xffffff'
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'
  #selection:
  #  text: '0xeaeaea'
  #  background: '0x404040'
  #normal:
  #  black:   '0x000000'
  #  red:     '0xd54e53'
  #  green:   '0xb9ca4a'
  #  yellow:  '0xe6c547'
  #  blue:    '0x7aa6da'
  #  magenta: '0xc397d8'
  #  cyan:    '0x70c0ba'
  #  white:   '0xeaeaea'
  #bright:
  #  black:   '0x666666'
  #  red:     '0xff3334'
  #  green:   '0x9ec400'
  #  yellow:  '0xe7c547'
  #  blue:    '0x7aa6da'
  #  magenta: '0xb77ee0'
  #  cyan:    '0x54ced6'
  #  white:   '0xffffff'
  #dim:
  #  black:   '0x000000'
  #  red:     '0x8c3336'
  #  green:   '0x7a8530'
  #  yellow:  '0x97822e'
  #  blue:    '0x506d8f'
  #  magenta: '0x80638e'
  #  cyan:    '0x497e7a'
  #  white:   '0x9a9a9a'

background_opacity: 0.95

#selection:
  # When set to `true`, selected text will be copied to the primary clipboard.
  #save_to_clipboard: false

cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
  unfocused_hollow: true

live_config_reload: true

#shell:
#  program: /bin/bash
#  args:
#    - --login

#working_directory: None
#alt_send_esc: true

mouse:
  #double_click: { threshold: 300 }
  #triple_click: { threshold: 300 }
  hide_when_typing: false

  #url:
    #launcher:
    #  program: xdg-open
    #  args: []
    #modifiers: None

#mouse_bindings:
#  - { mouse: Middle, action: PasteSelection }

key_bindings:
  # (Windows, Linux, and BSD only)
  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
  #- { key: Insert,   mods: Shift,         action: PasteSelection   }
  - { key: Key0,     mods: Control,       action: ResetFontSize    }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Add,      mods: Control,       action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  - { key: Delete,   chars: "\x1b[3~"                              }

